SKILLS = {
    "python": ["python"],
    "java": ["java"],
    "c++": ["c++"],
    "sql": ["sql"],
    "html": ["html"],
    "css": ["css"],
    "javascript": ["javascript", "js"],
    "react": ["react"],
    "node": ["node", "nodejs"],
    "django": ["django"],
    "flask": ["flask"],
    "git": ["git"],
    "github": ["github"],
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning"],
    "data analysis": ["data analysis"],
    "data science": ["data science"],
    "artificial intelligence": ["artificial intelligence", "ai"],
    "nlp": ["nlp", "natural language processing"],
    "computer vision": ["computer vision"],
    "tensorflow": ["tensorflow"],
    "pytorch": ["pytorch"],
    "keras": ["keras"],
    "automation": ["automation"],
    "streamlit": ["streamlit"],
    "docker": ["docker"],
    "cloud": ["cloud"]
}
